# The settings in this file are identical to those in `piccolo.toml`, except
# as noted in the `[graphviz]` section.

[src.piccolo]
type = "bsv"
src-files = [ "../Piccolo/src_Core/*/*.bsv" ]
ast-file = "tutorial/piccolo.cbor.gz"
library-packages = [
    "ActionSeq", "Array", "Assert", "Clocks", "ConfigReg", "Connectable",
    "Counter", "Enum", "Environment", "FIFO", "FIFOF", "FIFOF_", "FIFOLevel",
    "FShow", "FoldFIFO", "FoldFIFOF", "Fork", "GetPut", "Inout", "LevelFIFO",
    "List", "ListN", "Once", "Prelude", "PreludeBSV", "Probe", "ProbeWire",
    "RWire", "Real", "RegFile", "Reserved", "RevertingVirtualReg", "Vector",
]


[graphviz]
out-dir = "piccolo-arch"
# To get a lower-level view, we enable display of nets and combinational logic
# elements.
draw-nets = true        # was false
draw-logics = true      # was false
draw-ext-ports = true
draw-logic-ports = true
dedup-edges = true
shorten-net-names = true
