# The settings in this file are identical to those in `piccolo.toml`, except
# as noted in the `[graphviz]` section.

[src.piccolo]
type = "bsv"
src-files = [ "../Piccolo/src_Core/*/*.bsv" ]
ast-file = "tutorial/piccolo.cbor.gz"
library-packages = [
    # BSV Prelude
    "ActionSeq", "Array", "Assert", "Clocks", "ConfigReg", "Connectable",
    "Counter", "Enum", "Environment", "FIFO", "FIFOF", "FIFOF_", "FIFOLevel",
    "FShow", "FoldFIFO", "FoldFIFOF", "Fork", "GetPut", "Inout", "LevelFIFO",
    "List", "ListN", "Once", "Prelude", "PreludeBSV", "Probe", "ProbeWire",
    "RWire", "Real", "RegFile", "Reserved", "RevertingVirtualReg", "Vector",

    # BSV Libraries
    "BGetPut", "BitonicSort", "Boolify", "BRAM_Compat", "BRAMCore", "CGetPut",
    "ClientServer", "CompletionBuffer", "DPSRAM", "DReg", "EqFunction",
    "Esl_defs", "FlexBitArith", "IVec", "LFSR", "ListFIFO", "ListReg", "Mcp",
    "ModuleAugmented", "OInt", "OVLAssertions", "PopCount", "Pull", "Push",
    "RAM", "RegTwo", "RPush", "SplitTRAM", "SPSRAM", "SRAM", "SRAMFile",
    "StmtFSM", "STRAM", "SVA", "SyncSRAM", "Tabulate", "ToString", "TRAM",
    "TriState", "TurboFIFO", "UIntRange", "UniqueWrappers", "Wallace", "ZBus",
    "ZBusUtil",

    # `Near_Mem_Caches` is part of Piccolo, but architecture extraction
    # currently enters an infinite loop when trying to process it.
    # TODO: Remove this
    "Near_Mem_Caches",
]


[graphviz]
out-dir = "piccolo-arch"
# To get a higher-level view, we disable display of individual module ports.
draw-nets = false
draw-logics = false
draw-ext-ports = false      # was true
draw-logic-ports = false    # was true
dedup-edges = true
shorten-net-names = true
