# The settings in this file are identical to those in `piccolo.toml`, except
# as noted in the `[graphviz]` section.

[src.piccolo]
type = "bsv"
src-files = [
    "../gfe/bluespec-processors/P1/Piccolo/src_Core/*/*.bsv",
    "../gfe/bluespec-processors/P1/Piccolo/src_Testbench/*/*.bsv",
    "../gfe/bluespec-processors/P1/Piccolo/src_Testbench/*/*/*.bsv",
]
ast-dir = "tutorial/piccolo/ast-cache"
bsc-config-flags = [
    "-D", "RV32",
    "-D", "ISA_PRIV_M",
    "-D", "ISA_PRIV_U",
    "-D", "ISA_I",
    "-D", "ISA_M",
    "-D", "ISA_A",
    "-D", "ISA_C",
    "-D", "SHIFT_SERIAL",
    "-D", "MULT_SYNTH",
    "-D", "Near_Mem_Caches",
    "-D", "FABRIC64",
]

[design]
root-module = "Top_HW_Side.mkTop_HW_Side"


[graphviz]
out-dir = "piccolo-arch"
# To get a lower-level view, we enable display of nets and combinational logic
# elements.
draw-nets = true        # was false
draw-logics = true      # was false
draw-ext-ports = true
draw-logic-ports = true
dedup-edges = true
shorten-net-names = true
