variables:
  gfe_id: 380
  testgen_id: 273
  PERSONAL_ACCESS_TOKEN: "warning! If you can see this, I have not been set in the CI/CD Variables UI"

default:
  before_script:
    - |
      set +e
      eval $(ssh-agent -s)
      ssh-add <(echo "$SSH_PRIVATE_KEY")

      export RISCV=/opt/riscv
      export PATH=/opt/riscv/bin:$PATH
      export PATH=/opt/Xilinx/Vivado/2019.1/bin:/opt/Xilinx/Vivado_Lab/2019.1/bin:$PATH
      source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      source /opt/Xilinx/Vivado_Lab/2019.1/settings64.sh
      export XILINXD_LICENSE_FILE=/opt/Xilinx/Xilinx.lic
    - |
      # Sanity check
      nix-shell --command 'which vivado_lab'


benchmarks:
  stage: .post
  tags: ["nix"]
  script:
    - >-
      nix-shell --command '
      besspin-unpack-coremark-builds;
      gfe-run-elf --help;
      gfe-run-elf chisel_p1 --elf coremark-builds/coremark-p1.bin --timeout 60 --expected "Correct operation validated";
      gfe-run-elf bluespec_p1 --elf coremark-builds/coremark-p1.bin --timeout 60 --expected "Correct operation validated";
      gfe-run-elf chisel_p2 --elf coremark-builds/coremark-p2.bin --timeout 60 --expected "Correct operation validated";
      gfe-run-elf bluespec_p2 --elf coremark-builds/coremark-p2.bin --timeout 60 --expected "Correct operation validated"'
