#!@bash@/bin/bash
set -e

piccolo="$1"
fmjson="$2"

usage() {
    echo "usage: $0 </path/to/piccolo/> <piccolo.fm.json.configured>"
    exit 1
}
[ -d "$piccolo" ] || usage
[ -f "$fmjson" ] || usage


cfg="$(@coreutils@/bin/mktemp)"
cleanup() {
    rm -f "$cfg"
}
trap cleanup EXIT


cat >"$cfg" <<EOF
Piccolo
topfile = src_SSITH_P1/src_BSV/P1_Core.bsv
:src_SSITH_P1/src_BSV
EOF

@fmtoolWrapper@/bin/besspin-feature-model-tool list-enabled "$fmjson" >>"$cfg"

@python3@/bin/python3 @systemBuilder@/build.py "$piccolo" piccolo-build "$cfg"
