#!@bash@/bin/bash
set -e

die() {
    echo "$@"
    exit 1
}

[[ "$#" -eq "2" ]] || die "usage: $0 </path/to/piccolo/> <piccolo.fm.json.configured>"

piccolo="$1"
fmjson="$2"

[ -d "$piccolo" ] || die "error: $piccolo is not a directory"
[ -f "$fmjson" ] || die "error: $fmjson is not a file"


cfg="$(@coreutils@/bin/mktemp)"
cleanup() {
    rm -f "$cfg"
}
trap cleanup EXIT


cat >"$cfg" <<EOF
Piccolo
topfile = src_SSITH_P1/src_BSV/P1_Core.bsv
:src_SSITH_P1/src_BSV
EOF

@fmtoolWrapper@/bin/besspin-feature-model-tool list-enabled "$fmjson" >>"$cfg"

@python3@/bin/python3 @systemBuilder@/build.py "$piccolo" piccolo-build "$cfg"
