#!/bin/sh

DEVICE=vda1
FILE=initramfs.cpio.gz

echo "chainloader: booting from $DEVICE"

mkdir -v -p /chain/dev /chain/new /chain/mnt
mount -v -t devtmpfs none /chain/dev
mount -v -t vfat /chain/dev/$DEVICE /chain/mnt
mount -v -t tmpfs none /chain/new

echo "chainloader: unpacking initramfs.cpio.gz"
cd /chain/new
gunzip -c /chain/mnt/initramfs.cpio.gz | cpio -i

echo "chainloader: switching root"
exec switch_root /chain/new /init

echo "chainloader: failed to switch_root"
exit 1
