[src.piccolo]
type = "bsv"
src-files = [
    "src_Core/*/*.bsv",
    "src_Testbench/*/*.bsv",
    "src_Testbench/*/*/*.bsv",
]
ast-dir = "ast"

bsc-config-flags = [
    "-D", "RV32",
    "-D", "ISA_PRIV_M",
    "-D", "ISA_PRIV_U",
    "-D", "ISA_I",
    "-D", "ISA_M",
    "-D", "ISA_A",
    "-D", "ISA_C",
    "-D", "SHIFT_SERIAL",
    "-D", "MULT_SYNTH",
    "-D", "Near_Mem_Caches",
    "-D", "FABRIC64",
]

[design]
root-module = "Top_HW_Side.mkTop_HW_Side"

[graphviz]
draw-nets = false
draw-logics = false
draw-ext-ports = false
draw-logic-ports = false
draw-muxes = "collapse"
draw-repacks = "fwd-only"
dedup-edges = true
shorten-net-names = true
draw-onesided-nets = false

