#!/bin/bash
set -e

if [ "$#" -ne 2 ]; then
    echo "usage: $0 <repo-url> <debian-urls.txt> >files.nix"
fi

repo_url=$1
repo_url=${repo_url%/}

echo "# AUTO-GENERATED FILE - DO NOT EDIT"
echo "# Generated by $0 on $(date)"
echo "# Repo URL: $repo_url"
echo

echo '['
while read path; do
    path=${path#/}
    # Sanitize basename.  Debian versions sometimes contain `~`, which is not
    # allowed in nix store paths.
    name=$(basename "$path")
    name=${name//[~%]/_}
    sha256=$(nix-prefetch-url --name "$name" "$repo_url/$path")
    decpath=$(echo "$path" | python -c 'if True:
        import sys, urllib
        sys.stdout.write(urllib.unquote(sys.stdin.read()))
    ')
    echo "{ name = \"$name\"; relPath = \"$decpath\"; url = \"$repo_url/$path\"; sha256 = \"$sha256\"; }"
done <$2
echo ']'
